import Link from 'next/link';
import { db, ensureTalentTable } from '@/lib/db';
import { seedTalent, type Talent } from '@/lib/talent';

async function getTalent(): Promise<Talent[]> {
  if (!db) return seedTalent;
  try {
    await ensureTalentTable();
    const rows = await db`SELECT talent_handle AS "talentHandle", name, bio, category, discipline, pfp, socials FROM northline_talent_profiles WHERE public_status='published' ORDER BY created_at ASC`;
    return rows.length ? rows as Talent[] : seedTalent;
  } catch { return seedTalent; }
}
export const metadata={title:'Talent',description:'Meet the creators, competitive players, and digital talent represented by Northline.'};
export default async function TalentPage(){
 const talent=await getTalent();
 return <><a className="skip-link" href="#main-content">Skip to main content</a><header id="siteHeader"><Link href="/" className="logo"><img src="/assets/logo-mark.png" alt=""/>Northline</Link><nav className="primary-nav"><div className="nav-links"><Link href="/talent" className="active">Talent</Link><Link href="/team.html">Team</Link><Link href="/past-work.html">Past Work</Link><Link href="/services.html">Services</Link><Link href="/work.html">For Brands</Link><Link href="/about.html">About</Link></div><Link href="/apply.html" className="btn btn-primary">Apply ↗</Link></nav></header><main id="main-content"><section className="page-hero"><div className="page-hero-bg"/><div className="wrap"><div className="eyebrow">Northline <span className="dot">/</span> Talent</div><h1>The people<br/>we <em>represent.</em></h1><p className="page-sub">Browse the Northline roster. Open a profile for public links and representation context.</p></div></section><section className="talent-showcase"><div className="wrap"><div className="section-heading reveal"><div><div className="section-number">01 / ROSTER</div><h2>Find your<br/><em>talent.</em></h2></div><p>{talent.length} represented profiles.</p></div><div className="talent-grid talent-grid-five reveal">{talent.map((p,i)=><Link className="talent-card talent-card-link" href={`/talent/${p.talentHandle}`} key={p.talentHandle}><div className="talent-card-top"><span>{String(i+1).padStart(2,'0')}</span><span>{p.discipline.toUpperCase()}</span></div><span className="talent-photo">{p.pfp&&<img src={p.pfp} alt={p.name}/>}</span><div><h3>{p.name}</h3><p>{p.bio||p.discipline}</p><span className="talent-social">@{p.talentHandle} ↗</span></div></Link>)}</div><div className="roster-note"><span>ROSTER NOTE</span><p>Profiles show public information only. Performance figures are added only when verified and intentionally published.</p></div></div></section><section className="dark-section"><div className="wrap"><div className="section-heading reveal"><div><div className="section-number">02 / REPRESENTATION</div><h2>Built around<br/><em>talent.</em></h2></div></div><div className="points-grid reveal"><div><span>01</span><h3>Opportunities</h3><p>We identify opportunities that fit the talent, audience, and direction.</p></div><div><span>02</span><h3>Partnerships</h3><p>We help turn brand conversations into useful partnerships.</p></div><div><span>03</span><h3>Support</h3><p>Direct communication, planning, and operational support.</p></div><div><span>04</span><h3>Long-term</h3><p>We're building careers and relationships, not one-off moments.</p></div></div></div></section><section className="final-cta"><div className="wrap final-cta-inner reveal"><div className="section-number">NEXT / NORTHLINE</div><h2>Let's build<br/><em>what's next.</em></h2><p>Looking for representation, talent, or a partnership? Start the conversation.</p><Link href="/apply.html" className="btn btn-primary">Apply to Northline ↗</Link></div></section></main></>}