import Link from 'next/link';
import { seedTalent } from '@/lib/talent';

export const metadata={title:'Talent',description:'Meet the creators, competitive players, and digital talent represented by Northline.'};

export default function TalentPage(){return <main id="main-content">
<section className="page-hero"><div className="page-hero-bg"/><div className="wrap"><div className="eyebrow">Northline <span className="dot">/</span> Talent</div><h1>The people<br/>we <em>represent.</em></h1><p className="page-sub">Browse the Northline roster. Open a profile for public links and representation context.</p></div></section>
<section className="talent-showcase"><div className="wrap"><div className="section-heading reveal"><div><div className="section-number">01 / ROSTER</div><h2>Find your<br/><em>talent.</em></h2></div><p>Creators and competitive players represented by Northline.</p></div><div className="talent-grid talent-grid-five reveal">{seedTalent.map((person,index)=><Link className="talent-card talent-card-link" key={person.talentHandle} href={`/talent/${person.talentHandle}`}><div className="talent-card-top"><span>{String(index+1).padStart(2,'0')}</span><span>{person.discipline.toUpperCase()}</span></div><span className="talent-photo">{person.pfp&&<img src={person.pfp} alt={person.name}/>}</span><div><h3>{person.name}</h3><p>{person.category==='Creator'?'Content creator.':'Competitive Fortnite player.'}</p><span className="talent-social">{person.socials.x?.replace('https://x.com/','@')} ↗</span></div></Link>)}</div><div className="roster-note"><span>ROSTER NOTE</span><p>Profiles show public information only. Performance figures are added only when verified and intentionally published.</p></div></div></section>
<section className="brand-overview"><div className="wrap"><div className="section-heading reveal"><div><div className="section-number">02 / FOR BRANDS</div><h2>Need talent?<br/><em>Start here.</em></h2></div><Link href="/work" className="text-link">Brand partnerships →</Link></div><div className="brand-mini-grid reveal"><div><span>01</span><h3>Browse</h3><p>Review represented talent and identify who fits your audience.</p></div><div><span>02</span><h3>Match</h3><p>Northline identifies relevant talent for the opportunity.</p></div><div><span>03</span><h3>Build</h3><p>We coordinate the partnership around the talent and brand.</p></div></div></div></section>
<section className="dark-section"><div className="wrap"><div className="section-heading reveal"><div><div className="section-number">03 / REPRESENTATION</div><h2>What talent<br/><em>gets.</em></h2></div></div><div className="points-grid reveal"><div><span>01</span><h3>Opportunities</h3><p>We help identify and manage opportunities that fit the talent and direction.</p></div><div><span>02</span><h3>Partnerships</h3><p>We handle brand conversations and help turn partnerships into something useful.</p></div><div><span>03</span><h3>Support</h3><p>Direct communication, planning, and operational help that keeps everything moving.</p></div><div><span>04</span><h3>Long-term</h3><p>We're building careers and relationships, not chasing one-off moments.</p></div></div></div></section>
<section className="final-cta"><div className="wrap final-cta-inner reveal"><div className="section-number">NEXT / NORTHLINE</div><h2>Let's build<br/><em>what's next.</em></h2><p>Looking for representation, talent, or a partnership? Start the conversation.</p><Link href="/apply" className="btn btn-primary">Apply to Northline →</Link></div></section>
</main>}
